### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/beechj01/workspace/tv-wall-pong/Users/beechj01/workspace'

### ISSUE THREAD

**Issue by johnbeech** [guileen/project-switcher#21]
[Enter steps to reproduce below:]

1. Add two project folders to the left hand bar (e.g. /workspace/tv-wall-pong/ and /workspace/product-monitor/)
2. Press Cmd+; to switch
3. The error "/Users/beechj01/workspace/tv-wall-pong/Users/beechj01/workspace" appeared

**Atom Version**: 0.209.0
**System**: Mac OS X 10.8.5
**Thrown From**: [project-switcher](https://github.com/guileen/project-switcher) package, v0.2.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/beechj01/workspace/tv-wall-pong/Users/beechj01/workspace'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir '/Users/beechj01/workspace/tv-wall-pong/Users/beechj01/workspace'
    at Error (native)
    at Object.fs.readdirSync (fs.js:805:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
    at Object.exports.getSiblingProjects (/Users/beechj01/.atom/packages/project-switcher/lib/utils.coffee:15:16)
    at Object.exports.listProjects (/Users/beechj01/.atom/packages/project-switcher/lib/utils.coffee:9:20)
    at ProjectSwitcherView.module.exports.ProjectSwitcherView.show (/Users/beechj01/.atom/packages/project-switcher/lib/project-switcher-view.coffee:69:27)
    at ProjectSwitcherView.module.exports.ProjectSwitcherView.toggle (/Users/beechj01/.atom/packages/project-switcher/lib/project-switcher-view.coffee:49:21)
    at atom-workspace.<anonymous> (/Users/beechj01/.atom/packages/project-switcher/lib/project-switcher-view.coffee:21:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
```

### Commands

```
  2x -0:41.4.0 project-switcher:toggle (atom-text-editor.editor.is-focused)
     -0:28.4.0 autocomplete-plus:cancel (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:26 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:26 core:cancel (atom-text-editor.editor.is-focused)
     -0:22.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:14.4.0 project-switcher:toggle (atom-text-editor.editor.is-focused)
     -0:03.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.5.0 project-switcher:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-mheg-plus, v0.3.4
minimap, v4.10.0
pretty-json, v0.3.3
project-switcher, v0.2.3

# Dev
No dev packages
```

**Comment by piascikj** [comment]
same error for me

**Comment by ricardofbarros** [comment]
This could be a issue of permissions, be sure the parent directory you are working on have sufficient permissions

**Comment by piascikj** [comment]
I think it has to do with two project folders being open at once.  Permissions are fine

**Comment by ricardofbarros** [comment]
Yeah that is a known issue maybe I should put it on readme, if you have two project folders open it doesn't play well with this [line](https://github.com/guileen/project-switcher/blob/master/lib/utils.coffee#L8)

And honestly I don't known if this should be ever supported (having 2 projects), but however I could always disable the pane when you have 1+ projects opened.

The usage of this package should rely on having only 1 project opened in your workspace and switch between projects that belong to the same parent.

I'm open to new ideas/strategies to tackle this problem, so what are your thoughts on this?
