### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\projects\project.local\C:\projects

### ISSUE THREAD

**Issue by thecfguy** [guileen/project-switcher#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [project-switcher](https://github.com/guileen/project-switcher) package, v0.3.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\projects\project.local\C:\projects'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir 'C:\projects\project.local\C:\projects'
    at Error (native)
    at Object.fs.readdirSync (fs.js:805:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
    at Object.exports.getSiblingProjects (C:\Users\pritesh\.atom\packages\project-switcher\lib\utils.coffee:15:16)
    at Object.exports.listProjects (C:\Users\pritesh\.atom\packages\project-switcher\lib\utils.coffee:9:20)
    at ProjectSwitcherView.module.exports.ProjectSwitcherView.show (C:\Users\pritesh\.atom\packages\project-switcher\lib\project-switcher-view.coffee:69:27)
    at ProjectSwitcherView.module.exports.ProjectSwitcherView.toggle (C:\Users\pritesh\.atom\packages\project-switcher\lib\project-switcher-view.coffee:49:21)
    at atom-workspace.<anonymous> (C:\Users\pritesh\.atom\packages\project-switcher\lib\project-switcher-view.coffee:21:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\pritesh\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
    at C:\Users\pritesh\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
```
### Commands

```
     -0:03.8.0 project-switcher:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:00.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "C:\\projects"
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-html-preview, v0.1.10
atom-typescript, v5.0.29
language-cfml, v0.8.7
linter, v1.2.4
project-manager, v1.15.11
project-switcher, v0.3.0

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
My guess is that the culprit is this config:

``` json
{
  "core": {
    "projectHome": "C:\\projects"
  }
}
```
