### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by stjohnjohnson** [guileen/project-switcher#7]
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10
**Thrown From**: [project-switcher](https://github.com/guileen/project-switcher) package, v0.1.0

### Steps To Reproduce

1. When I have a project open
2. And I open the switcher

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5506

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at ProjectSwitcherView.jQuery.fn.extend.remove (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5506:21)
  at ProjectSwitcherView.jQuery.fn.extend.detach (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5608:15)
  at ProjectSwitcherView.module.exports.ProjectSwitcherView.toggle (/Users/stjohn/.atom/packages/project-switcher/lib/project-switcher-view.coffee:31:8)
  at atom-workspace.<anonymous> (/Users/stjohn/.atom/packages/project-switcher/lib/project-switcher-view.coffee:10:63)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by ricardofbarros** [comment]
Does this still happens?

**Comment by stjohnjohnson** [comment]
Not sure, I stopped using this package. :(

**Comment by ricardofbarros** [comment]
All bugs were fixed, on the last minor release, I will close this then.
